import React from "react";

export const Favicons = () => (
  <>
    <link
      rel="shortcut icon"
      href={`/${process.env.NEXT_PUBLIC_REPO_NAME}/favicons/favicon.ico`}
    />
    <link
      rel="icon"
      sizes="16x16 32x32 64x64"
      href={`/${process.env.NEXT_PUBLIC_REPO_NAME}/favicons/favicon.ico`}
    />
    <link
      rel="icon"
      type="image/png"
      sizes="196x196"
      href={`/${process.env.NEXT_PUBLIC_REPO_NAME}/favicons/favicon-192.png`}
    />
    <link
      rel="icon"
      type="image/png"
      sizes="160x160"
      href={`/${process.env.NEXT_PUBLIC_REPO_NAME}/favicons/favicon-160.png`}
    />
    <link
      rel="icon"
      type="image/png"
      sizes="96x96"
      href={`/${process.env.NEXT_PUBLIC_REPO_NAME}/favicons/favicon-96.png`}
    />
    <link
      rel="icon"
      type="image/png"
      sizes="64x64"
      href={`/${process.env.NEXT_PUBLIC_REPO_NAME}/favicons/favicon-64.png`}
    />
    <link
      rel="icon"
      type="image/png"
      sizes="32x32"
      href={`/${process.env.NEXT_PUBLIC_REPO_NAME}/favicons/favicon-32.png`}
    />
    <link
      rel="icon"
      type="image/png"
      sizes="16x16"
      href={`/${process.env.NEXT_PUBLIC_REPO_NAME}/favicons/favicon-16.png`}
    />
    <link
      rel="apple-touch-icon"
      href={`/${process.env.NEXT_PUBLIC_REPO_NAME}/favicons/favicon-57.png`}
    />
    <link
      rel="apple-touch-icon"
      sizes="114x114"
      href={`/${process.env.NEXT_PUBLIC_REPO_NAME}/favicons/favicon-114.png`}
    />
    <link
      rel="apple-touch-icon"
      sizes="72x72"
      href={`/${process.env.NEXT_PUBLIC_REPO_NAME}/favicons/favicon-72.png`}
    />
    <link
      rel="apple-touch-icon"
      sizes="144x144"
      href={`/${process.env.NEXT_PUBLIC_REPO_NAME}/favicons/favicon-144.png`}
    />
    <link
      rel="apple-touch-icon"
      sizes="60x60"
      href={`/${process.env.NEXT_PUBLIC_REPO_NAME}/favicons/favicon-60.png`}
    />
    <link
      rel="apple-touch-icon"
      sizes="120x120"
      href={`/${process.env.NEXT_PUBLIC_REPO_NAME}/favicons/favicon-120.png`}
    />
    <link
      rel="apple-touch-icon"
      sizes="76x76"
      href={`/${process.env.NEXT_PUBLIC_REPO_NAME}/favicons/favicon-76.png`}
    />
    <link
      rel="apple-touch-icon"
      sizes="152x152"
      href={`/${process.env.NEXT_PUBLIC_REPO_NAME}/favicons/favicon-152.png`}
    />
    <link
      rel="apple-touch-icon"
      sizes="180x180"
      href={`/${process.env.NEXT_PUBLIC_REPO_NAME}/favicons/favicon-180.png`}
    />
    <meta name="msapplication-TileColor" content="#FFFFFF" />
    <meta
      name="msapplication-TileImage"
      content={`/${process.env.NEXT_PUBLIC_REPO_NAME}/favicons/favicon-144.png`}
    />
    <meta
      name="msapplication-config"
      content={`/${process.env.NEXT_PUBLIC_REPO_NAME}/browserconfig.xml`}
    />
  </>
);
